# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Shopee gen

on:
  schedule:
    - cron: "0 * * * *"
  watch:
    types: [started]
# on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
    
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NAME: ${{ secrets.NAME }}
          envkey_TOKEN: ${{ secrets.TOKEN }}
          envkey_SHOPEE_TOKEN: ${{ secrets.SHOPEE_TOKEN }}
          envkey_DEVICE_ID: ${{ secrets.DEVICE_ID }}
          envkey_USER_ID: ${{ secrets.USER_ID }}
          envkey_LANGUAGE: ${{ secrets.LANGUAGE }}
          envkey_U_TOKEN: ${{ secrets.U_TOKEN }}
          envkey_HELP: ${{ secrets.HELP }}
          directory: './'
          file_name: '.env'  

      - name: Install dependencies
        run: node
      - run: yarn

      - name: Install dependencies
        run: yarn add axios 

      - run: node ./src/cron/checkin.js
      - run: node ./src/cron/live.js
      - run: node ./src/cron/luckydraw.js
      - run: node ./src/cron/water.js
      - run: node ./src/cron/boardgame.js
