# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Shopee gen

# on:
  # schedule:
  #   - cron: "0 */2 * * *"
  # watch:
  #   types: [started]
on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
    
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          INPUT_ENVKEY_NAME: ${{ secrets.NAME }}
          INPUT_ENVKEY_TOKEN: ${{ secrets.TOKEN }}
          INPUT_ENVKEY_SHOPEE_TOKEN: ${{ secrets.SHOPEE_TOKEN }}
          INPUT_ENVKEY_DEVICE_ID: ${{ secrets.DEVICE_ID }}
          INPUT_ENVKEY_USER_ID: ${{ secrets.USER_ID }}
          INPUT_ENVKEY_LANGUAGE: ${{ secrets.LANGUAGE }}
          INPUT_ENVKEY_U_TOKEN: ${{ secrets.U_TOKEN }}
          INPUT_ENVKEY_HELP: ${{ secrets.HELP }}
          directory: './'
          file_name: '.env'
          

      - name: Install dependencies
        run: node
      - run: yarn

      - name: Install dependencies
        run: yarn add axios 

     
                

      - run: node ./src/cron/checkin.js
      - run: node ./src/cron/live.js
      - run: node ./src/cron/luckydraw.js
      - run: node ./src/cron/water.js
      - run: node ./src/cron/boardgame.js
